# Generated by Django 3.0.8 on 2020-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=20)),
            ],
        ),
    ]
