# Generated by Django 3.0.8 on 2020-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
